import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientProvider from "../provider/clientprovider";
import Header from "../components/Header";
import Footer from "../components/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Providers({ children }) {
  return (
    <ClientProvider>
      {children}
    </ClientProvider>
  );
}

export default function RootLayout({ children }) {
  return (
    <html>
      <body className={`${geistSans.variable} ${geistMono.variable} font-sans  w-full h-screen min-h-screen`}>
        <Providers>
          <Header/>
          <main className="flex-grow">{children}</main>
          <Footer/>
        </Providers>
      </body>
    </html>
  );
}

